name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      - run: dotnet test --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t ghcr.io/varvara14522/is-lab-app:test .

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push with tags
        run: |
          SHORT_SHA=${{ github.sha }}
          SHORT_SHA=${SHORT_SHA:0:7}
          docker build -t ghcr.io/varvara14522/is-lab-app:latest -t ghcr.io/varvara14522/is-lab-app:$SHORT_SHA .
          docker push ghcr.io/varvara14522/is-lab-app:latest
          docker push ghcr.io/varvara14522/is-lab-app:$SHORT_SHA
